### ISSUE TITLE
Please update Readme file

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#12]
I want to try your plugin, but project Readme is making me confused.
There is this line:

> Autocompletion! (using autocomplete+). Will be obsolete! Check out: atom-autocomplete-gdscript by neikeq

atom-autocomplete-gdscript is dead - last update was 3 years ago.
Also It don't say with version of gdscript are supported.

**Comment by PrestonKnopp** [comment]
Hey, thanks posting an issue! I’ll update the README. It is very outdated.

Highlighting will work for godot 3.1 but the docs are outdated so basic autocomplete is inaccurate.

Just FYI, I’m working on a update to the grammar and a new autocompletion engine based on Atom’s tree-sitter parser that will work with all versions of gdscript.

**Comment by PrestonKnopp** [comment]
Hey, I updated the readme. I also pushed a new update that should now highlight for typed gdscript. The autocomplete "docs" are still out of date but I will be updating that soon.

**Comment by jebedaia360** [comment]
No I'm feel bad that I didn't report it issue earlier - from some time I use vscode and it's plugin good-tool, but is dead - last update was 8 months ago  :( 
I event try to make my vscode clone in godot it self, but I can't make autocomplete to work.
https://github.com/jebedaia360/GDCoder/blob/master/ScriptEdit/ScriptEdit.gd

**Comment by jebedaia360** [comment]
Also It is possible to make plugin to your plugin?
I make advanced addon for godot and want to make autocomplete to support it.
This project: https://github.com/jebedaia360/Rakugo

**Comment by PrestonKnopp** [comment]
I welcome issues so don't hesitate to post them! I didn't know the vscode plugin was dead. It's a really nice tool. Also, smart use of ClassDB for getting autocomplete suggestions.

> Also It is possible to make plugin to your plugin?
> I make advanced addon for godot and want to make autocomplete to support it.

What did you have in mind for it's autocomplete?

**Comment by jebedaia360** [comment]
> Also, smart use of ClassDB for getting autocomplete suggestions.

Thanks, but  it don't want to works :(

> What did you have in mind for it's autocomplete?

Auto complete for singletons/autoloads.
So this addon of mine create dictionary of global available variables using `Rakugo.define("name", value)`- autocomplete their names in other *Rakugo* methods.
Also my addon have methods that use dictionary of arguments instead of just arguments - so I want to have auto complete for this `{"arg_name": value}` pair.
And also in feature I want to make *RakugoScript*  similar language to *Ren'Py Langue* with possibility to use *GDScript* blocks in side it.

And sorry I didn't make separated issue for this.

**Comment by PrestonKnopp** [comment]
> Auto complete for singletons/autoloads.

Nice, this is in the works.

> So this addon of mine create dictionary of global available variables using Rakugo.define("name", value)- autocomplete their names in other Rakugo methods.
> Also my addon have methods that use dictionary of arguments instead of just arguments - so I want to have auto complete for this {"arg_name": value} pair.

I believe that both of these can be done.

> And also in feature I want to make RakugoScript similar language to Ren'Py Langue with possibility to use GDScript blocks in side it.

This could be done by writing a tree-sitter-rakugo-script parser. [Tree-Sitter](https://github.com/tree-sitter/tree-sitter) is the parser engine i'm using for GDScript. The reason I bring this up is that tree sitter can import other tree-sitter parsers. Additionally the syntax tree that tree-sitter produces can be used to transpile RakugoScript to GDScript, C++, or whatever language one has the time to write. I'm also willing to help write the parser for rakugo if you would like to go that path.

> And sorry I didn't make separated issue for this.

Actually, that's a good idea. Could you open a new issue with all requested features when you have a moment?

Once the autocompletion is stable enough I will start refactoring while factoring in the Rakugo autocomplete stuff!

**Comment by jebedaia360** [comment]
> Actually, that's a good idea. Could you open a new issue with all requested features when you have a moment?

I made new issue for this here: #15
