### ISSUE TITLE
It doesn't recognize enum's values that ends with number

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#18]
Like you see on this screen shot, `VECT2`, `VECT3`, `VECT4` are white which shows that they aren't recognized as enum's values. So it doesn't show them in autocomplete.
![image](https://user-images.githubusercontent.com/1294815/60239780-2640f200-98af-11e9-993e-9898aabbe92b.png)

**Comment by PrestonKnopp** [comment]
Hey, thanks for posting an issue! This should now be fixed with: 8a2ac49

It has been published on atom.io
