### ISSUE TITLE
VSCode port

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#19]
@PrestonKnopp 
If you think how hard it would be to make port of this for vscode, I would try to do it?
Can you point me to some good tutorials about CoffieScript?

**Comment by jebedaia360** [comment]
never mind

**Comment by PrestonKnopp** [comment]
Hey, I’ve been thinking of extracting the gdscript completion into its own library. That way any editor can use it. Even wrap it in a language server.

That brings me to another thought: I believe the godot team is working on a native language server implementation built into godot that will obviate the development of external completion libraries.

The developer for the popular VSCode plugin has no plans as of now to update it to support typed GDScript which is understandable as it’s made almost entirely of RegExes, he’s most likely busy, and the aforementioned native LS.

There’s also another person who created a simple but looks to be fully working, LS from an engine fork.

The developer of a vim gdscript plugin has also made a completion service. I haven’t checked to see how they did it.

As of now, this completion service(on the develop and my local branches) can:

- lazily index files as needed
- solve types
- index autoloads
- index scenes
- index project files
- use any documentation version
- supports typed and non-typed gdscript

Also I want to have domain specific support such as for Rakugo, maybe make a plugin interface.

All in all I’m not sure what I should do with this completion service as it may be a waste of time.

What do you think?

**Comment by jebedaia360** [comment]
So I'm you think that porting it for vscode can be waste of time yes?
It just was a loose thought - this is way I close it after I open it XD
Also I wrote it before I discover that there is new godot addon for vscode.
I think that you are probably right, unfortunate time isn't infinite :( , 
plugin interface is good idea.
You could add to your addon tool bar that open project in godot, run project, run chosen godot scene.

**Comment by jebedaia360** [comment]
@PrestonKnopp ⬆️  Hello?

**Comment by PrestonKnopp** [comment]
I’m still going to work on it. It’s a fun project and I think it allows it to be more experimental and it’s not constrained to godot’s release cycle.

**Comment by Geequlim** [comment]
The gdscript langugae server is now implemented in godot as an godot editor plugin. It is now a part of godot editor. And the VSCode plugin is updated to support most of the required features.
I think this can be closed now.
