### ISSUE TITLE
I must Rebuild for new Atom

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#20]
New atom version ask me to rebuild your package (made it to fast for screenshot):
![image](https://user-images.githubusercontent.com/1294815/61723588-b23e2080-ad6c-11e9-8559-3049bd325616.png)

**Comment by PrestonKnopp** [comment]
I'm not sure why it would do that. Did atom update around that time?

**Comment by PrestonKnopp** [comment]
Closing as I don't think this in itself is an issue.

**Comment by PrestonKnopp** [comment]
It is an issue, what am I saying.

**Comment by jebedaia360** [comment]
XD, yes atom update around this time.

**Comment by PrestonKnopp** [comment]
Okay I added new builds. Hopefully this resolves the issue of having to rebuild for macos and win. The new build will still have to be downloaded when updating to the latest version of atom.

If you have a minute, could you reinstall lang-gdscript to verify it installs correctly?

**Comment by jebedaia360** [comment]
So I check on Linux  and it install without a problem
