### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by apecoder1** [PrestonKnopp/language-gdscript#22]
The error below appears whenever I try to install the plugin from within the Atom editor. I already checked for python and everything seems ok. Sorry if I seem dumb, I am trying Linux for the first time.
`Installing “lang-gdscript@4.1.2” failed.Hide output…

> tree-sitter-gdscript@0.2.3 install /tmp/apm-install-dir-11978-13953-19cj2xp.5agt/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 5.0.0-23-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11978-13953-19cj2xp.5agt/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11978-13953-19cj2xp.5agt/package.json'
npm WARN apm-install-dir-11978-13953-19cj2xp.5agt No description
npm WARN apm-install-dir-11978-13953-19cj2xp.5agt No repository field.
npm WARN apm-install-dir-11978-13953-19cj2xp.5agt No README data
npm WARN apm-install-dir-11978-13953-19cj2xp.5agt No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-gdscript@0.2.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-gdscript@0.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/somar/.atom/.apm/_logs/2019-08-08T06_19_59_055Z-debug.log
`

By the way, I tried to find this file or even this location and was unable. Even using search through dolphin.

**Comment by apecoder1** [comment]
Sorry, it seems it really was something that an unix amateur like me would get wrong.

I searched the term "node-gyp" and found out it has something to do with nodejs. I ended up installing it, and tried installing again and everything went fine. Thank you for this. Your plugin is really helpfull.

**Comment by PrestonKnopp** [comment]
Hi, thanks for posting an issue.

From the output it looks like your system was missing some build tools like `make`, but I'm not certain. I'm thinking that installing node-gyp came with it's dependencies and fixed this issue.

> Sorry if I seem dumb

Not at all. Good luck with your new linux distro!
