### ISSUE TITLE
Rebuild package failed.

### ISSUE THREAD

**Issue by theblacktiger59** [PrestonKnopp/language-gdscript#26]
Hello,
I have updated Atom to 1.41.0. (os: Windows 10)
I have installed the lang-gdscript 4.1.2.
Get me a message with an invitation to rebuild the package. Which fail.

![Screenshot_592](https://user-images.githubusercontent.com/35955523/68735130-af1ab900-0617-11ea-9dda-c43c79e5a12f.png)

**Comment by PrestonKnopp** [comment]
Hey, thanks for posting an issue. Can you try reinstalling the package to see if that resolves the issue?

**Comment by theblacktiger59** [comment]
Tried that, same message.
Although the module seems to work as I can see the syntax colors of a *.gd file as normal.

**Comment by PrestonKnopp** [comment]
Could you post the whole error log as text?

It should still work as it can fall back to the legacy text-mate grammar.

**Comment by theblacktiger59** [comment]
Sure thing, here comes : 
(if you mean another log, let me know. I'm not all that familiar with Atom)

> prebuild-install WARN install EBUSY: resource busy or locked, open 'C:\Users\2Lux\.atom\packages\lang-gdscript\node_modules\tree-sitter-gdscript\build\Release\tree_sitter_gdscript_binding.node'
gyp ERR! clean error 
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\2Lux\.atom\packages\lang-gdscript\node_modules\tree-sitter-gdscript\build\Release\tree_sitter_gdscript_binding.node'
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\2Lux\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\2Lux\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\2Lux\.atom\packages\lang-gdscript\node_modules\tree-sitter-gdscript
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-gdscript@0.2.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-gdscript@0.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\2Lux\.atom\.apm\_logs\2019-11-13T05_37_49_543Z-debug.log

**Comment by PrestonKnopp** [comment]
Awesome, thanks. That's what I was looking for.

**Comment by PrestonKnopp** [comment]
Hey, so I'm not sure why it's failing.

You could try manually deleting these folders:
 
`C:\Users\2Lux\.atom\packages\lang-gdscript` and
`C:\Users\2Lux\.npm\_prebuilds`

And then reinstall lang-gdscript.

> prebuild-install WARN install EBUSY: resource busy or locked

I haven't seen this error before. After googling, it seems to be caused by antivirus software.

See: https://github.com/npm/npm/issues/13461
See: https://github.com/felixrieseberg/windows-build-tools/issues/119

Let me know if I can be of more assistance and if this issue gets resolved.

**Comment by theblacktiger59** [comment]
`C:\Users\2Lux\.atom\packages\lang-gdscript ` deleted.
I don't have any folder : `C:\Users\2Lux\.npm\_prebuilds`
I do have : `C:\Users\2Lux\.atom\.apm\_prebuilds` if it is the one you meant ?

- With just the lang-gdscript folder deleted, no change.
- I use TinyWall firewall to complement WindowsDefender, I tried turning both of them off, no change.

Checked those two other issues thread, couldn't find anything helpful either.
I may try to reinstall Atom completely tomorrow and see.

Thank you already for the assistance sofar.

**Comment by PrestonKnopp** [comment]
> C:\Users\2Lux\.atom\.apm\_prebuilds if it is the one you meant ?

Yes, my bad, that's the one I meant.

Thanks for helping debug this. If the issue persists, I recommend checking out VSCode with the Godot tools plugin.

**Comment by theblacktiger59** [comment]
Deleting both folder, still no change.
Deinstalling Atom, deleting the whole .atom folder under my users/name directory, reinstalling : no change.
Thanks for the recommendation, but since it works anyway in Atom, I'll keep using it. :)

**Comment by PrestonKnopp** [comment]
> Deleting both folder, still no change.
> Deinstalling Atom, deleting the whole .atom folder under my users/name directory, reinstalling : no change.

That's a bummer :(

> Thanks for the recommendation, but since it works anyway in Atom, I'll keep using it. :)

I'm glad to have you using the plugin! When Godot v3.2 is released I'll push out the language server client which has rich autocompletion. It's great!

**Comment by theblacktiger59** [comment]
Language server, that will be great indeed ! looking forward to it.

**Comment by theblacktiger59** [comment]
Quick update : Version 5.0.0 of the package doesn't trigger any error ! Yah !
Could not update, I had to manually delete the package and install again.
I think the problem is with my system / atom ... anyway.
Cheers, thank for the good work. ;-)

**Comment by PrestonKnopp** [comment]
Thanks for the update! I'm glad it works :) Huh, I wonder what's causing those underlying issues?

5.0.0 also has the language server client, so if you're using Godot v3.2+ you can try it out by enabling it in the package settings.

**Comment by theblacktiger59** [comment]
I got similar error message `resource busy or locked` with other packages.
No idea why, it's beyond my knowledge.
I do want to use the language server, but I'm using godot for production so I don't dare to move to v3.2+ until a stable release.
