### ISSUE TITLE
Quiet mode + auto toggle connection to Godot Language Sever

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#29]
As you know I work on Rakugo framework, which is one big plugin and set of custom, mostly `tool` nodes. 
So it this often causes crashes when I make some big changes.
It gives big popup with message that it can connect to server every time I open new script and godot just was  closed, or I don't open godot yet - it is irritating.
- so it should be in seting option to turn on **quiet** mode - with out this message, or or it would display them as a warning.
- after crash auto completion is broken so it should switch back to old one  auto completion mechanism, and switch back again when connection to server was successful.
- also I just notice that when I turn off connecting to sever in settings it still tries to connect to sever util I restart Atom.

**Comment by PrestonKnopp** [comment]
Thank you for posting an issue. I appreciate the feedback!

> so it should be in seting option to turn on quiet mode - with out this message, or or it would display them as a warning.

I'll add a "Don't show again" button to the disconnected notification and a setting to undo it.

> after crash auto completion is broken so it should switch back to old one auto completion mechanism, and switch back again when connection to server was successful.
>
> also I just notice that when I turn off connecting to sever in settings it still tries to connect to sever util I restart Atom.

Since 3.2 is now the stable version, I'll remove the "Use Godot Language Server" setting and instead try connecting a couple times before falling back to the basic completer.

**Comment by PrestonKnopp** [comment]
Hey, I actually ended up doing a good bit of cleaning up.

- I got rid of the notifications all together, I don't think they added anything to the UX and you can use the busy-signal package.
- It now connects to language server and if it fails will fallback to the basic completer.
- It will attempt to connect when you open a gdscript file.
- Added command 'Show Language Client Status'.
- Fixed datatips not showing. They work great now.

Let me know what you think!
