### ISSUE TITLE
Godot LS not connecting

### ISSUE THREAD

**Issue by BlueCannonBall** [PrestonKnopp/language-gdscript#31]
I went through all the instructions in the readme and the LS just dosen't connect.

**Comment by PrestonKnopp** [comment]
Hey, thanks for posting an issue.

Are there any errors printing in the dev tools console? You can open the dev tools with the command "Window: Toggle Dev Tools" from the command palette.

Make sure both atom and lang-gdscript are up to date. This package's current version is: `v5.1.0`. 

This package's releases will only work with Godot *v3.2.stable* and *v3.2.1.stable*. If you are using a custom build after commit [24b2704](https://github.com/godotengine/godot/commit/24b27043fec7ef9a4baf2c5ecab67fc20563b586) you will have to use the [lang-gdscript feature/lsc-tcp-socket branch](https://github.com/PrestonKnopp/language-gdscript/tree/feature/lsc-tcp-socket).

Some things to note:
- The language client will only activate:
  - for files on disk
  - when a project folder is added to atom
- Check the language client status from command palette: "Lang GDScript: Show Language Client Status"
- The language client will try connecting when opening a gdscript file in a tab.
  - After opening Godot with your project, close and reopen your gdscript tabs.
