### ISSUE TITLE
wont install

### ISSUE THREAD

**Issue by astrale-sharp** [PrestonKnopp/language-gdscript#32]
Hey there, i run linux mint and whenever i try to install this atom package via gui
or via shell "apm install lang-gdscript"
i tried 
-installing nvm and "$ nvm install node ; nvm use node"
-reinstalling atom

If you have any hack, i'll take it thanks a lot ;)

thank you!

 I get the following error :

$ apm install lang-gdscript
Installing lang-gdscript to /home/astrale/.atom/packages ✗

> tree-sitter-gdscript@0.2.5 install /tmp/apm-install-dir-120313-5448-boe6jl.ikqmb/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript
> prebuild-install || node-gyp rebuild

make : on entre dans le répertoire « /tmp/apm-install-dir-120313-5448-boe6jl.ikqmb/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript/build »
  CXX(target) Release/obj.target/tree_sitter_gdscript_binding/src/scanner.o
tree_sitter_gdscript_binding.target.mk:107: recipe for target 'Release/obj.target/tree_sitter_gdscript_binding/src/scanner.o' failed
make : on quitte le répertoire « /tmp/apm-install-dir-120313-5448-boe6jl.ikqmb/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript/build »

prebuild-install WARN install No prebuilt binaries found (target=4.2.7 runtime=electron arch=x64 libc= platform=linux)
make: g++: Command not found
make: *** [Release/obj.target/tree_sitter_gdscript_binding/src/scanner.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120313-5448-boe6jl.ikqmb/node_modules/lang-gdscript/node_modules/tree-sitter-gdscript
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120313-5448-boe6jl.ikqmb/package.json'
npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-120313-5448-boe6jl.ikqmb No description
npm WARN apm-install-dir-120313-5448-boe6jl.ikqmb No repository field.
npm WARN apm-install-dir-120313-5448-boe6jl.ikqmb No README data
npm WARN apm-install-dir-120313-5448-boe6jl.ikqmb No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-gdscript@0.2.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-gdscript@0.2.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/astrale/.atom/.apm/_logs/2020-04-13T17_43_40_233Z-debug.log

**Comment by PrestonKnopp** [comment]
Hi, thanks for posting an issue.

Since I haven't uploaded prebuilds for linux you will have to install some extra tools to compile tree sitter.

Can you run: `apt update && apt install build-essential g++` and then try reinstalling lang-gdscript?

**Comment by astrale-sharp** [comment]
wow, that fixed it good job!

**Comment by astrale-sharp** [comment]
well that fixed it, good job!
