### ISSUE TITLE
Installing "lang-gdscript@5.1.1" failed

### ISSUE THREAD

**Issue by Abb1x** [PrestonKnopp/language-gdscript#35]
lang-gdscript does not install on my system 
OS: Ubuntu 20.04 
Atom: 1.46.0
here are the logs : 
![image](https://user-images.githubusercontent.com/54687179/84044169-3396a580-a975-11ea-9bdd-21931162d5a6.png)

**Comment by PrestonKnopp** [comment]
Hey, thanks for posting an issue. I'm not sure why this would happen. Can you attach the complete debug log?

Also, try updating to the latest atom version. Right now it's `1.47.0`. Although it should work for `1.46.0`.

**Comment by Abb1x** [comment]
Ok

**Comment by Abb1x** [comment]
The issue was the version,I reinstalled atom to update it and it worked

**Comment by PrestonKnopp** [comment]
Thank you for letting me know!
