### ISSUE TITLE
Feature Request: Adding Setting to load legacy text-mate grammar as default at .gd files.

### ISSUE THREAD

**Issue by Jean28518** [PrestonKnopp/language-gdscript#44]
Hey,

at first great work.

Atom is connected to the GoDot Language server but doesn't do syntax highlighting:
![grafik](https://user-images.githubusercontent.com/39700889/102698187-d3de5880-423b-11eb-8e42-d0b2a85a5dff.png)

For me that's okay, I don't need such fancy autocomplete.
It would be great, if you could add a setting that this automtatic connecting to the GoDot Language Server is disabled per default, and the default grammar of .gd files is the GDScript (Legacy Textmate Grammar) instead. 

Thank you very much!

Greetings
Jean

**Comment by Rockster160** [comment]
👍  To this. The file server is extremely slow and causes my Atom to freeze every time I try to make a change. All I want is some reasonable syntax highlighting. Anything extra should be an option.

**Comment by PrestonKnopp** [comment]
Hi, thanks for posting an issue and I apologize for the late response.

> add a setting that this automtatic connecting to the GoDot Language Server is disabled per default

I can add a setting for this. It will be an opt-out setting as it is probably a better user experience (when it works) to have the language client automatically connect.

> default grammar of .gd files is the GDScript (Legacy Textmate Grammar) instead

I won't make the legacy grammar the default as it is being phased out. Also, I'd like to improve the tree-sitter (GDScript) grammar.

When the GDScript grammar stops working I appreciate the issues raised. I don't follow atom, electron, or node's releases so the ABI versions often differ from the GDScript builds.

**Comment by Jean28518** [comment]
Thanks for your answer!
For me the problem is fixed, now everything is working fine. 
Thanks for adding the Q&A in your addon description!

**Comment by PrestonKnopp** [comment]
Cool, I'm glad the problem is fixed. I added a setting that allows the language server client to be disabled, too.
