### ISSUE TITLE
Files other than .gd are being linted, causing errors.

### ISSUE THREAD

**Issue by KettLovahr** [PrestonKnopp/language-gdscript#45]
Potentially a duplicate of, or the same root cause as #38? Opening files such as `.gitignore` or `*.import` or `export_presets.cfg`, causes them to be linted and make errors appear, which persist after these files are closed.

![image](https://user-images.githubusercontent.com/25535207/115127016-cd71aa80-9fa9-11eb-8dd8-3e2078da6a82.png)

![image](https://user-images.githubusercontent.com/25535207/115127066-fd20b280-9fa9-11eb-90ec-c205c99a8a35.png)

I'm not quite sure if it's a mistake on my part, or if it's an issue with the client, but I can't think of anything I could do to work around this issue, save for turning off linting altogether, I can't find a way to blacklist files that I don't want linted.

It's also always reproducible on my end: as soon as Godot is open, the Language Server is up and one of these files are open in Atom, the false errors appear.

Ideally, only `*.gd` files should be linted with the `gdscript` provider.

I don't think versions are relevant here, but I can provide them if necessary.

Thanks in advance!

**Comment by PrestonKnopp** [comment]
Hi, thanks for posting an issue. This has been fixed in commit 74fb457 and will be pushed soon with version 6.2.
