### ISSUE TITLE
incompatible tree-sitter language version 

### ISSUE THREAD

**Issue by uniqueusername** [PrestonKnopp/language-gdscript#51]
running 6.2.0 and the current latest version of atom (1.58.0), this error shows up in the atom console with this package installed:
```Uncaught (in promise) RangeError: Incompatible language version. Compatible range: 9 - 12. Got: 13```

i was able to find other mentions of the same error in atom and tree-sitter related threads (e.g. https://github.com/tree-sitter/tree-sitter/issues/966#issuecomment-792987978). it seems that the most recent version of tree-sitter (0.19.x) being used in atom is not necessarily backwards compatible with some older grammars and the grammar this package uses may be one of those. i haven't been able to downgrade my atom's version of tree-sitter to see if this resolves the issue, but it may be indicative of some migration this package needs for its grammar to be compatible with the latest version of atom.

**Comment by PrestonKnopp** [comment]
Hey, thanks for finding and researching this. I reverted the tree-sitter grammars back to tree-sitter v0.17.3, rebuilt, and published.

Hopefully, this package is working again with v6.3.0. Let me know if there's anymore issues.

Thanks again!

**Comment by uniqueusername** [comment]
looks like that fixed it ! thank you-
